### PR TITLE
chore: ignore .db files and remove strict types from config files

### PR DESCRIPTION
**Pull request by DevVali**

### CODE REVIEW

**Comment by tenmajkl** [comment]
Strict types should be either everywhere or nowhere and for this project I would rather let the user pick what they want and ship it by default without it. Once I add cs-fixer there will be commented rule for strict types.

**Comment by DevVali** [comment]
Thank you for your correction! I was curious because they are being used [in the http config](https://github.com/Lemon-Framework/app/blob/master/config/http.php).

**Comment by tenmajkl** [comment]
Can you please remove it from all configs?

**Comment by DevVali** [comment]
Done. 👍

**Pull request merged**
